#ifndef _UTILS_OP_CODES_H_
#define _UTILS_OP_CODES_H_

typedef enum {
    HANDSHAKE_QUERY_MASTER,
    HANDSHAKE_WORKER_MASTER,
    HANDSHAKE_WORKER_STORAGE,
    RESULTADO_HANDSHAKE,
    ASIGNACION_QUERY_MASTER_WORKER //Ex: PATH_MASTER_WORKER
} op_code;

#endif