#ifndef _UTILS_OP_CODES_H_
#define _UTILS_OP_CODES_H_

typedef enum
{
    HANDSHAKE_QUERY_MASTER,
    HANDSHAKE_WORKER_MASTER,
    HANDSHAKE_WORKER_STORAGE,
    RESULTADO_HANDSHAKE,
    PATH_MASTER_WORKER,
    SOLICITUD_EJECUCION
} op_code;

#endif