#ifndef _UTILS_OP_CODES_H_
#define _UTILS_OP_CODES_H_

typedef enum
{
    HANDSHAKE_QUERY_MASTER,
    HANDSHAKE_WORKER_MASTER,
    HANDSHAKE_WORKER_STORAGE,
    RESULTADO_HANDSHAKE,
    ASIGNACION_WORKER, // Ex: PATH_MASTER_WORKER
    SOLICITUD_STORAGE,
    CONSULTA_INTERRUPCION,
    INSTRUCCION_STORAGE,
    INSTRUCCION_MASTER,
    PAGINA_WORKER,
    LECTURA_MASTER,
    SOLICITUD_EJECUCION,
    QUERY_FINALIZADA,
    NOTIF_QUERY_CONTROL,
    DESALOJO_QUERY,
    QUERY_DESALOJADA
} op_code;

typedef enum
{
    NOTIF_READ,
    NOTIF_FINAL
} notif_query_control;

#endif